services:
  segmentation:
    build: ./docker/otb/
    image: cartovegetation-otb
    volumes:
      # Main Script
      - C:/Users/decau/Documents/Informatique/cartovegetation/batch11_cartovegetation/scripts/seg.py:/app/app.py
      # Data
      - <HOST DATA PATH>:/app/data
  hte:
    build: ./docker/otb/
    image: cartovegetation-otb
    volumes:
      # Main Script
      - C:/Users/decau/Documents/Informatique/cartovegetation/batch11_cartovegetation/scripts/hte.py:/app/app.py
      # Data
      - <HOST DATA PATH>:/app/data
  rdi:
    build: ./docker/otb/
    image: cartovegetation-otb
    volumes:
      # Main Script
      - C:/Users/decau/Documents/Informatique/cartovegetation/batch11_cartovegetation/scripts/rdi.py:/app/app.py
      # Data
      - <HOST DATA PATH>:/app/data