services:
  seg:
    build: ./docker/otb/
    image: cartovegetation-otb
    environment:
      - otb.env
    volumes:
      # Main Script
      - ${PROJECT_ABSOLUTE_FOLDERPATH}/scripts/seg.py:/app/app.py
      # Data
      - ${DATA_ABSOLUTE_FOLDERPATH}:/app/data
    
  hte:
    build: ./docker/otb/
    image: cartovegetation-otb
    environment:
      - otb.env
    volumes:
      # Main Script
      - ${PROJECT_ABSOLUTE_FOLDERPATH}/scripts/hte.py:/app/app.py
      # Data
      - ${DATA_ABSOLUTE_FOLDERPATH}:/app/data
  rdi:
    build: ./docker/otb/
    image: cartovegetation-otb
    environment:
      - otb.env
    volumes:
      # Main Script
      - ${PROJECT_ABSOLUTE_FOLDERPATH}/scripts/rdi.py:/app/app.py
      # Data
      - ${DATA_ABSOLUTE_FOLDERPATH}:/app/data
  # zst:
  #   build: ./docker/otb/
  #   image: cartovegetation-otb
  #   environment:
  #     - otb.env
  #   volumes:
  #     # Main Script
  #     - ${PROJECT_ABSOLUTE_FOLDERPATH}/scripts/zst.py:/app/app.py
  #     # Data
  #     - ${DATA_ABSOLUTE_FOLDERPATH}:/app/data