services:
  segmentation:
    build: ./docker/otb/
    image: cartovegetation-otb
    volumes:
      # Main Script
      - <HOST SEGMENTATION SCRIPT PATH>:/app/app.py
      # Data
      - <HOST DATA PATH>:/app/data
  hte:
    build: ./docker/otb/
    image: cartovegetation-otb
    volumes:
      # Main Script
      - <HOST HARALICK_TEXTURE_EXTRACTION SCRIPT PATH>:/app/app.py
      # Data
      - <HOST DATA PATH>:/app/data
  rdi:
    build: ./docker/otb/
    image: cartovegetation-otb
    volumes:
      # Main Script
      - <HOST RADIOMETRIC_INDICES SCRIPT PATH>:/app/app.py
      # Data
      - <HOST DATA PATH>:/app/data